# This document serves two purposes to allow us to easily keep them in sync.
# 1) This document is the configuration for the MarkdownLint action.
# 2) This document is also serves as the documentation style guidelines.

# Default state for all rules
default: true

# all lists use a `-`
MD004:
  style: dash

# allow tabs in code blocks (for Go)
MD010:
  code_blocks: false

# disable line length, prefer one sentence per line for PRs
MD013: false

# emphasis with underscore (`_emphasis_`)
MD049:
  style: underscore

# bold with asterisk (`**bold**`)
MD050:
  style: asterisk

# Each sentence should be on its own line.  This enables easier commenting on individual sentences.  This is not enforced by MarkdownLint.
